### ISSUE TITLE
High CPU Usage for Monitor Ping

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimiPlugin-monitor#2]
Ping uses subprocess' POpen. This appears to use large amounts of CPU resource.

**Comment by ghost** [comment]
Hi b1scuit-thi3f, I cant seem to replicate this on windows running a simple ping of 50 IP addresses and concurrency of 10. Is it possible that something else within the same flow is causing the CPU spike instead of the subprocess ping?
